version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: &weekly
      interval: "weekly"
      day: "monday"
    groups:
      minor-patch-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: *weekly
    commit-message:
      prefix: "ci"
      include: "scope"
